### ISSUE TITLE
Various Legend Suggestions

### ISSUE THREAD

**Issue by Guitarninja2** [wargame-engine/grim-darkness#100]
Rage Demons: Hunting Hound, can only go onto a War Dogs unit, gives a buff against Characters
Dark Elves: Dark Muse, can only go on an Overlord, gives him the other two Tactics at 1
Alien Cults:  Beloved Leader, gives aura of +2 courage
Battle Sisters: Living Saint, can only go on a Greater High Sister, gives Holy Saint and replaces Sister Tactics(2) with Saint Tactics (1)
Knight Lords:  Knight Leader.  Gives Knight Leader(1) ability, which lets you reroll 9+ to hit for an armiger or helverin

**Comment by Valgaav2** [comment]
Added 11/9/21
