### ISSUE TITLE
Corrupted Marines Subfactions

### ISSUE THREAD

**Issue by Guitarninja2** [wargame-engine/grim-darkness#94]
Naming conventions for Traitor Legions:
Excess - Emperor's Children
Siege - Iron Warriors
Terror - Night Lords
Rage - World Eaters
Pestilence - Death Guard
Psychic - Thousand Sons
Destruction - Black Legion
Devotion - Word Bearers
Stealth - Alpha Legion

Strats:
Excess: + to character vs. character (Character gains +2 to str and acc but can only target an enemy character?), + speed
Siege: Exists
Terror: +shock, -courage.  Hit does extra shock strat?  Definitely 'use when enemy tries to remove shock, they have -X to tests to do so this turn
Rage: Exists
Pestilence: Exists
Psychic: Exists
Destruction:  World Burner strat for major combat/shooting buffs, Will of War for more buffs if you outnumber who you attack
Devotion: Refluff Sisters strats
Stealth: Exists

Legends:
Butcher of Worlds (Rage): Can Fight Twice once per game?  Just enhanced Expert Fighter?
Flash of Terror (Excess): +3 Mv?  Just enhanced Quick Reflexes?
Arcane Focus (Psychic): +1 AP on Powers for the bearer
Plague-Hive:  +1 Sv, Add 3-4 ap- attacks?

**Comment by Valgaav2** [comment]
New subfactions added, strats added 11/9/21
