### ISSUE TITLE
Alien Swarm Subfactions

### ISSUE THREAD

**Issue by Guitarninja2** [wargame-engine/grim-darkness#98]
Alien Swarm focuses:
Kaiju: Extra attacks for models, boosts to monsters.  FnP Strat, at least.  What else to give Big Boys?
Swarm: Boosts to Courage to counter Shock, bonuses for outnumbering?  Steal from Destruction in Corrupted Marines for latter
Hunters: Lictors and Genestealers.  Ambush modification, Charge/Sprint bonuses.  +3" while charging, +d6 inches closer when showing up from Ambush?

**Comment by Valgaav2** [comment]
Finished
